name: Build & Deploy

on:
  push:
    branches: ['*'] # Run on all branches
    paths:
      - 'blog/**'
  pull_request:
    paths:
      - 'blog/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Install cargo-hack from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: marmite
      - name: Generate site
        run: marmite blog dist -v
      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 1
  publish:
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Upload Page Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: path
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
