name: Build

on:
  push:
    branches: ['*'] # Run on all branches
    paths:
      - 'blog/**'
  pull_request:
    paths:
      - 'blog/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rochacbruno/marmite
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
